# Generated by Django 5.1.6 on 2025-05-14 03:59

import alertfi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertfi', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[alertfi.validators.validate_email_domain]),
        ),
    ]
